export const bookList = [
    {title: 'Harry Potter', author_name: ['J.K. Rowling'], first_publish_year: 1997, cover_i: undefined, ratings_average: 4.5},
    {title: 'The Lord of the Rings', author_name: ['J.R.R. Tolkien'], first_publish_year: 1954, cover_i: undefined, ratings_average: 4.8},
    {title: 'The Hobbit', author_name: ['J.R.R. Tolkien'], first_publish_year: 1937, cover_i: undefined, ratings_average: 4.3}, 
    {title: 'The Great Gatsby', author_name: ['F. Scott Fitzgerald'], first_publish_year: 1925, cover_i: undefined, ratings_average: 4.1},
    {title: 'To Kill a Mockingbird', author_name: ['Harper Lee'], first_publish_year: 1960, cover_i: undefined, ratings_average: 4.4},
    {title: '1984', author_name: ['George Orwell'], first_publish_year: 1949, cover_i: undefined, ratings_average: 4.7},
    {title: 'The Catcher in the Rye', author_name: ['J.D. Salinger'], first_publish_year: 1951, cover_i: undefined, ratings_average: 4.2},
    {title: 'The Hunger Games', author_name: ['Suzanne Collins'], first_publish_year: 2008, cover_i: undefined, ratings_average: 4.6},
    {title: 'The Da Vinci Code', author_name: ['Dan Brown'], first_publish_year: 2003, cover_i: undefined, ratings_average: 4.9},
    {title: 'The Alchemist', author_name: ['Paulo Coelho'], first_publish_year: 1988, cover_i: undefined, ratings_average: 4.1},
    {title: 'The Kite Runner', author_name: ['Khaled Hosseini'], first_publish_year: 2003, cover_i: undefined, ratings_average: 4.3},
    {title: 'Life of Pi', author_name: ['Yann Martel'], first_publish_year: 2001, cover_i: undefined, ratings_average: 4.5},
    {title: 'The Book Thief', author_name: ['Markus Zusak'], first_publish_year: 2005, cover_i: undefined, ratings_average: 4.7},
    {title: 'The Help', author_name: ['Kathryn Stockett'], first_publish_year: 2009, cover_i: undefined, ratings_average: 4.9},
]