export const bookList = [
    {title: 'Harry Potter', author: 'J.K. Rowling', rating: 4.45, description: 'A boy named Harry learns he is a wizard', genre: 'fantasy', published_date: '16/07/2005', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Lord of the Rings', author: 'J.R.R. Tolkien', description: 'A boy named Harry learns he is a wizard', rating: 4.48, genre: 'fantasy', published_date: '29/07/1954', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Hobbit', author: 'J.R.R. Tolkien', rating: 4.27, description: 'A boy named Harry learns he is a wizard', genre: 'fantasy', published_date: '21/09/1937', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'And Then There Were None', author: 'Agatha Christie', description: 'A boy named Harry learns he is a wizard', rating: 4.24, genre: 'mystery', published_date: '06/11/1939', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Da Vinci Code', author: 'Dan Brown', rating: 3.82, description: 'A boy named Harry learns he is a wizard', genre: 'mystery', published_date: '02/03/2003', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Alchemist', author: 'Paulo Coelho', rating: 3.86, description: 'A boy named Harry learns he is a wizard', genre: 'fantasy', published_date: '01/01/1988', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Catcher in the Rye', author: 'J.D. Salinger', rating: 3.79, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '16/07/1951', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Hunger Games', author: 'Suzanne Collins', rating: 4.33, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '14/09/2008', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Kite Runner', author: 'Khaled Hosseini', rating: 4.28, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '29/05/2003', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Book Thief', author: 'Markus Zusak', rating: 4.37, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '14/09/2005', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', rating: 3.91, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '10/04/1925', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
    {title: 'The Fault in Our Stars', author: 'John Green', rating: 4.24, description: 'A boy named Harry learns he is a wizard', genre: 'fiction', published_date: '10/01/2012', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/51UoqRAxwEL._SX331_BO1,204,203,200_.jpg'},
]